services:
  app:
    build: .
    container_name: microservice-videos-app
    volumes:
      - ./:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: ./.docker/nginx
    container_name: microservice-videos-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    build: ./.docker/postgres
    container_name: microservice-videos-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_DB: code_micro_videos
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: microservice-videos-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
